services:
    sound-extractor:
        container_name: ${PROJECT_NAME}-sound-extractor
        env_file:
            - .env.local
        build:
            dockerfile: ./Dockerfile
            args:
                SERVICE_PORT: 5000
                SERVICE_NAME: sound-extractor
        restart: unless-stopped
        networks:
            - api_network
        volumes:
            - ./:/app
        command: celery -A src.main.celery worker --loglevel=info --queues=api_to_sound_extractor
        ports:
            - "5000:5000"

networks:
  api_network:
    name: api_network
    driver: bridge
